# Generated by Django 2.1 on 2019-02-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Command',
            new_name='GPIO',
        ),
    ]
