# Generated by Django 2.1 on 2019-02-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190209_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpio',
            old_name='GPIO',
            new_name='GPIO_Pin',
        ),
    ]
