# Generated by Django 2.2.1 on 2019-05-27 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190209_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='trained_version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension', models.CharField(max_length=5)),
                ('filename', models.CharField(max_length=2000)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='generated_joke',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=3000)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('generated_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trained_version')),
            ],
        ),
    ]
